services:
  web:
    build:
      context: ./services/summaries
      dockerfile: Dockerfile.prod
      ssh:
        - default
    env_file:
      - .envdev
    depends_on:
      - web-db
    ports:
      - 8000:8000
  web-db:
    build:
      context: ./services/summaries/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
