services:
  web:
    build:
      context: ./services/summaries
      dockerfile: Dockerfile.prod
      ssh:
        - default
    environment:
      - ENVIRONMENT=prod
      - TESTING=0
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    ports:
      - 8000:8000
