#!/bin/bash

cat <<EOF
ENVIRONMENT=${API_ENVIRONMENT}
TESTING=0
DATABASE_URL=${DATABASE_URL}
DATABASE_TEST_URL=${DATABASE_TEST_URL}
CLIENT_ORIGIN_URL=${CLIENT_ORIGIN_URL}
JWT_TEST_ENCODE_KEY=${JWT_TEST_ENCODE_KEY}
TAVILY_API_KEY=${TAVILY_API_KEY}
OPENAI_API_KEY=${OPENAI_API_KEY}
AUTH0_DOMAIN=${AUTH0_DOMAIN}
AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
AUTH0_CLIENT_ID=${TEST_AUTH0_CLIENT_ID}
AUTH_CLIENT_SECRET=${TEST_AUTH0_CLIENT_SECRET}
JWT_TEST_TOKEN_MEMBER=
JWT_TEST_TOKEN_ADMIN=
TEST_MEMBER_PASSWORD=${AUTH0_TEST_MEMBER_PASSWORD}
TEST_ADMIN_PASSWORD=${AUTH0_TEST_ADMIN_PASSWORD}
EOF
