#!/bin/bash

cat <<EOF
WATCHPACK_POLLING=${WATCHBACK_POLLING}
NODE_ENV=${NODE_ENV}
REACT_APP_API_SERVER_URL=${API_URL}
REACT_APP_AUTH0_DOMAIN=${AUTH0_DOMAIN}
REACT_APP_AUTH0_CLIENT_ID=${REACT_AUTH0_CLIENT_ID}
REACT_APP_AUTH0_CALLBACK_URL=${REACT_APP_AUTH0_CALLBACK_URL}
REACT_APP_AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
EOF
