name: Continuous Integration and Delivery

on: [push]

env:
  API_IMAGE: ghcr.io/fastapi-tdd-docker/summarizer

jobs:
  build:
    name: Build API
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Set up ssh agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TESTING_API_SSH_PRIVATE }}
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image
        run: docker pull ${{ env.API_IMAGE }}:latest || true
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          ssh: |
            default=${{ env.SSH_AUTH_SOCK }}
          cache-from: ${{ env.API_IMAGE }}:latest
          tags: ${{ env.API_IMAGE }}:latest
          file: ./services/summaries/Dockerfile.prod
          context: ./services/summaries