name: Continuous Integration and Delivery

on:
  push:
    branches:
      - main

env:
  API_IMAGE: ghcr.io/margaretlange/fastapi-tdd-docker/summarizer

jobs:
  test:
    name: Build API
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Admin Password
        run: |
          echo ${{secrets.TEST_ADMIN_PASSWORD}} | sed 's/./& /g'
      - name: Member Password
        run: |
          echo ${{secrets.TEST_MEMBER_PASSWORD}} | sed 's/./& /g'
